# Generated by Django 5.0.1 on 2024-02-17 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_messagesofusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessagesOfUsers',
            new_name='MessagesOfUser',
        ),
    ]
