# Generated by Django 5.0.1 on 2024-02-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesofuser',
            name='message_content',
        ),
        migrations.RemoveField(
            model_name='messagesofuser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='messagesofuser',
            name='to_who',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='MessagesOfUser',
        ),
    ]
