# Generated by Django 5.0.1 on 2024-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesofuser',
            name='message_content',
            field=models.ManyToManyField(blank=True, to='chats.chat'),
        ),
    ]
