# Generated by Django 5.0.1 on 2024-02-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_liked_by'),
        ('users', '0007_profile_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='like', to='posts.post'),
        ),
    ]
