# Generated by Django 5.0.1 on 2024-02-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_comment'),
        ('users', '0010_remove_profile_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='posts.comment'),
        ),
    ]
