# Generated by Django 5.0.1 on 2024-02-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comments',
        ),
    ]
