# Generated by Django 5.0.1 on 2024-02-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_comment_post_comments'),
        ('users', '0012_remove_profile_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='posts.comment'),
        ),
    ]
