# Generated by Django 5.0.1 on 2024-02-07 18:11

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=time.time),
        ),
    ]
