# Generated by Django 5.0.1 on 2024-02-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
