# Generated by Django 5.0.1 on 2024-02-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_shared_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_time',
            field=models.TextField(blank=True, max_length=18),
        ),
    ]
