# Generated by Django 5.0.1 on 2024-02-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
