# Generated by Django 5.0.1 on 2024-02-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_slug',
            field=models.TextField(blank=True, max_length=18),
        ),
    ]
