# Generated by Django 5.0.1 on 2024-02-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_comment_comment_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
