# Generated by Django 5.0.1 on 2024-02-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_comment'),
        ('users', '0012_remove_profile_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
