# Generated by Django 5.0.1 on 2024-02-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_comment_post_comments'),
        ('users', '0014_remove_profile_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
