# Generated by Django 5.0.1 on 2024-02-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_comment_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_time',
        ),
    ]
